Interfaces/SysPec.App/Controllers/VacinaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SysPec.Data.Models;

namespace SysPec.App.Controllers
{
    [Authorize]
    public class VacinaController : Controller
    {
        [HttpGet]
        public ActionResult Index(int? VacinaId, VacinaMessageId? message)
        {
            ViewBag.StatusMessage =
            message == VacinaMessageId.AddSuccess ? "Vacina adicionada com sucesso."
            : message == VacinaMessageId.SaveSucess ? "Vacina atualizada com sucesso."
            : message == VacinaMessageId.Error ? "Ocorreu um erro durante a operação. Tente novamente mais tarde."
            : "";

            ViewBag.VacinaExiste = VacinaId.HasValue && VacinaId > 0;
            if (ViewBag.VacinaExiste)
                return View(Vacina.Get(VacinaId.Value));
            return View();
        }

        [HttpPost]
        public ActionResult Index(Vacina vacina)
        {
            VacinaMessageId message = VacinaMessageId.Error;
            int id = 0;
            try
            {
                if (vacina != null)
                {
                    if (vacina.Id > 0)
                    {
                        vacina.Save();
                        id = vacina.Id;
                        message = VacinaMessageId.SaveSucess;
                    }
                    else
                    {
                        vacina.Criador = Helpers.Current.CriadorId;
                        vacina.Add();
                        id = vacina.Id;
                        Helpers.Current.Vacinas = Vacinas.ListByCriador(Helpers.Current.CriadorId);
                        message = VacinaMessageId.AddSuccess;
                    }
                }
            }
            catch (Exception)
            {
                return RedirectToAction("Index", new { message = VacinaMessageId.Error });
            }
            return RedirectToAction("Index", new { VacinaId = id, message = message });
        }

        [HttpGet]
        public PartialViewResult Listar() 
        {
            ViewBag.Vacinas = Vacinas.ListByCriador(Helpers.Current.CriadorId);
            return PartialView();
        }
    }

    public enum VacinaMessageId
    {
        AddSuccess,
        SaveSucess,
        Error
    }
}

Interfaces/SysPec.App/Views/Vacina/Index.cshtml
@model SysPec.Data.Models.Vacina
@{
    ViewBag.Title = "Vacinas";
    Layout = "~/Views/Shared/_Master.cshtml";
}
@using (Html.BeginForm("Index", "Vacina", FormMethod.Post, new { role = "form" }))
{
    <p class="text-success text-center">@ViewBag.StatusMessage</p>
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.Criador)
    <div class="form-group">
        @Html.LabelFor(m => m.Nome)
        @Html.TextBoxFor(m => m.Nome, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Nome, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Anotacoes)
        @Html.TextAreaFor(m => m.Anotacoes, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Anotacoes, "", new { @class = "text-danger" })
    </div>
    <div class="row">
        <div class="col-sm-3">
            @if (ViewBag.VacinaExiste)
            {
                @Html.ActionLink("Nova Vacina", "Index", null, new { @class = "btn btn-lg btn-primary btn-block" })
            }
        </div>
        <div class="col-sm-6">
        </div>
        <div class="col-sm-3">
            <input type="submit" value="Salvar" class="btn btn-lg btn-success btn-block" />
        </div>
    </div>
}
<br />
@Html.Action("Listar")

Interfaces/SysPec.App/Views/Vacina/Listar.cshtml
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Vacinas cadastradas
            </div>
            <div class="panel-body">
                @if (ViewBag.Vacinas != null && ViewBag.Vacinas.Count > 0)
                {
                    <div class="table-responsive dataTable_wrapper">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-vacinas">
                            <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>Anotações</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @for (int i = 0; i < ViewBag.Vacinas.Count; i++)
                                {

                                    <tr class="@(i % 2 == 0 ? "odd" : "even") gradeA">
                                        <td>@ViewBag.Vacinas[i].Nome</td>
                                        <td>@SysPec.App.Helpers.Helper.GetSubString(ViewBag.Vacinas[i].Anotacoes, 80)</td>
                                        <td class="text-right">
                                            <a href="@Url.Action("Index", new { VacinaId = ViewBag.Vacinas[i].Id })" class="btn btn-primary btn-circle">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <script>
                        jQuery(function () {
                            $('#dataTables-vacinas').DataTable();
                        });
                    </script>
                }
                else
                {
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="alert alert-warning" role="alert">
                                <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>
                                <span class="sr-only">Atenção:</span>
                                Não existe vacinas cadastrados.
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>