Interfaces/SysPec.App/Controllers/AnimalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SysPec.Data.Models;

namespace SysPec.App.Controllers
{
    [Authorize]
    public class AnimalController : Controller
    {
        [HttpGet]
        public ActionResult Index(int? AnimalId, AnimalMessageId? message, bool? ApresentaBusca)
        {
            ViewBag.StatusMessage =
                    message == AnimalMessageId.AddSuccess ? "Animal adicionado com sucesso."
                    : message == AnimalMessageId.DisableSucess ? "Animal desabilitado com sucesso."
                    : message == AnimalMessageId.Error ? "Ocorreu um erro durante a operação. Tente novamente mais tarde."
                    : "";

            if (ApresentaBusca.HasValue && ApresentaBusca.Value)
            {
                ViewBag.ApresentaBusca = true;
            }
            else
            {
                ViewBag.ApresentaBusca = false;
                ViewBag.AnimalExiste = AnimalId.HasValue && AnimalId.Value > 0;
                if (ViewBag.AnimalExiste)
                {
                    return View(Animal.Get(AnimalId.Value));
                }
                else
                {
                    Lotes lotes = Lotes.List(Helpers.Current.FazendaId);
                    Lotes lotesDisponiveis = new Lotes();
                    foreach (Lote l in lotes)
                    {
                        if (LoteController._QtdMaxAnimais > Lote.GetQtnAnimais(l.Id))
                        {
                            lotesDisponiveis.Add(l);
                        }
                    }
                    ViewBag.LotesDisponiveis = lotesDisponiveis;
                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult Index(Animal model)
        {
            AnimalMessageId message = AnimalMessageId.Error;
            int id = 0;
            try
            {
                if (model != null)
                {
                    model.Add();
                    message = AnimalMessageId.AddSuccess;
                    id = model.Id;
                }
            }
            catch (Exception)
            {
                return RedirectToAction("Index", new { message = AnimalMessageId.Error });
            }
            return RedirectToAction("Index", new { AnimalId = id, message = message });
        }

        [HttpGet]
        public ActionResult Buscar()
        {
            return RedirectToAction("Index", new { ApresentaBusca = true });
        }

        [HttpGet]
        public PartialViewResult BuscaFormulario()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult Buscar(int TipoBusca, string ValorBusca)
        {
            Animais animais = new Animais();
            switch (TipoBusca)
            {
                case 1:
                    animais = Animais.ListAnimaisByCodigo(ValorBusca, Helpers.Current.FazendaId);
                    break;
                case 2:
                    animais = Animais.ListByLoteName(ValorBusca, Helpers.Current.FazendaId);
                    break;
            }
            TempData["animais"] = animais;
            TempData["ValorBusca"] = ValorBusca;
            return View();
        }

        [HttpPost]
        public ActionResult Desabilitar(int Id)
        {
            try
            {
                if (Id > 0)
                {
                    Animal.Disable(Id);
                    return RedirectToAction("Index", new { message = AnimalMessageId.DisableSucess });
                }
                else
                    return RedirectToAction("Index", new { message = AnimalMessageId.Error });
            }
            catch (Exception)
            {
                return RedirectToAction("Index", new { message = AnimalMessageId.Error });
            }
        }

        [HttpGet]
        public PartialViewResult ListByLote(int LoteId)
        {
            ViewBag.Titulo = "Animais do Lote";
            ViewBag.Animais = Animais.ListByLote(LoteId);
            return PartialView("Listar");
        }

        [HttpGet]
        public PartialViewResult ListByFazenda(int FazendaId)
        {
            ViewBag.Titulo = "Animais da Fazenda";
            ViewBag.Animais = Animais.ListByFazenda(FazendaId);
            return PartialView("Listar");
        }

        [HttpGet]
        public PartialViewResult Listar()
        {
            return PartialView();
        }

        public enum AnimalMessageId
        {
            AddSuccess,
            DisableSucess,
            Error
        }
    }
}

Interfaces/SysPec.App/Controllers/AplicacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SysPec.Data.Models;
using SysPec.App.Helpers;

namespace SysPec.App.Controllers
{
    [Authorize]
    public class AplicacaoController : Controller
    {
        [HttpGet]
        public ActionResult PorAnimal(int? AnimalId)
        {
            ViewBag.AnimalExiste = AnimalId.HasValue && AnimalId > 0;
            if (ViewBag.AnimalExiste)
                ViewBag.Animal = Animal.Get(AnimalId.Value);
            else 
            {
                Animais animais = Animais.ListByFazenda(Current.FazendaId);
                if (animais != null && animais.Count > 0)
                    ViewBag.Animais = animais;
                else
                    return RedirectToAction("ApresentaMensagem", new { menssagem = "Não existe animais disponíveis", message = MessageType.Warning });
            }
            return View();
        }

        [HttpGet]
        public ActionResult PorLote(int? LoteId)
        {
            ViewBag.LoteExiste = LoteId.HasValue && LoteId > 0;
            if (ViewBag.LoteExiste)
                ViewBag.Lote = Lote.Get(LoteId.Value);
            else 
            {
                Lotes lotes = Lotes.List(Current.FazendaId);
                ViewBag.Lotes = new Lotes();
                if (lotes != null && lotes.Count > 0)
                    foreach (Lote l in lotes)
                        if (Lote.GetQtnAnimais(l.Id) > 0)
                            ViewBag.Lotes.Add(l);
                if (ViewBag.Lotes.Count <= 0)
                    return RedirectToAction("ApresentaMensagem", new { menssagem = "Não existe lotes com animais disponíveis", message = MessageType.Warning });
            }
            return View();
        }

        [HttpGet]
        public ActionResult Editar()
        {
            Vacinas vacinas = Current.Vacinas;
            if (vacinas.Count <= 0)
                return RedirectToAction("ApresentaMensagem", new { menssagem = "Não existe vacinas cadastradas", message = MessageType.Warning });
            ViewBag.Vacinas = vacinas;
            return PartialView();
        }

        [HttpPost]
        public ActionResult Registrar(Aplicacao model) 
        {
            try
            {
                if (model != null)
                {
                    if (model.Animal > 0)
                    {
                        model.Add();
                    }
                    else
                    {
                        model.AddReplicandoParaLote();
                    }
                    return RedirectToAction("ApresentaMensagem", new { menssagem = "Vacinação registrada com sucesso!", message = MessageType.Sucess });
                }
                else 
                {
                    return RedirectToAction("ApresentaMensagem", new { menssagem = "Não foi possível registrar a vacinação. Dados invalídos!", message = MessageType.Warning });
                }
            }
            catch (Exception) 
            {
                return RedirectToAction("ApresentaMensagem", new { menssagem = "Desulpe! Não foi possível registrar a vacinação. Erro desconhecido!", message = MessageType.Error });
            }
        }

        [HttpGet]
        public ActionResult ApresentaMensagem(string menssagem, MessageType message)
        {
            ViewBag.Menssagem = menssagem;
            ViewBag.MessageType = message;
            return View();
        }

        [HttpGet]
        public PartialViewResult ListByAnimal(int AnimalId)
        {
            ViewBag.ApresentaDadoAnimais = false;
            ViewBag.Titulo = "Vacinas Aplicadas";
            ViewBag.Aplicacoes = Aplicacoes.ListByAnimal(AnimalId);
            return PartialView("Listar");
        }

        [HttpGet]
        public PartialViewResult ListByVacina(int VacinaId)
        {
            ViewBag.ApresentaDadoAnimais = true;
            Vacina vacina =  Vacina.Get(VacinaId);
            string titulo = string.Empty;
            if (vacina != null)
                titulo = string.Format("Animais vacinados ({0})", vacina.Nome);
            else
                titulo = "Animais vacinados";
            ViewBag.Titulo = titulo;
            ViewBag.Aplicacoes = Aplicacoes.ListByVacina(VacinaId,Current.FazendaId);
            return PartialView("Listar");
        }

        [HttpGet]
        public PartialViewResult Listar()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult Vacinacao()
        {
            ViewBag.Vacinas = Current.Vacinas;
            ViewBag.ApresantaResuldado = false;
            return View();
        }

        [HttpPost]
        public ActionResult Vacinacao(int VacinaId)        
        {
            ViewBag.Vacinas = Current.Vacinas;
            ViewBag.ApresantaResuldado = true;
            Vacina vacina = Vacina.Get(VacinaId);
            Aplicacoes aplicacoes = Aplicacoes.ListByVacina(VacinaId, Current.FazendaId);
            ViewBag.Aplicacoes = aplicacoes;
            ViewBag.ApresentaDadoAnimais = true;
            ViewBag.QuantidadeFazendaAnimais = Animais.ListCountAnimaisByFazenda(Current.FazendaId);
            return View();
        }

        [HttpGet]
        public PartialViewResult VacinacaoFormulario()
        {
            ViewBag.Vacinas = Current.Vacinas;
            return PartialView();
        }
    }
}

Interfaces/SysPec.App/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SysPec.Data.Models;
using SysPec.Data.Estatisticas;

namespace SysPec.App.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index(int? FazendaId)
        {
            if (FazendaId.HasValue && FazendaId.Value > 0) 
                Helpers.Current.FazendaId = FazendaId.Value;

            if (Helpers.Current.FazendaId > 0)
            {
                Fazenda f = Fazenda.Get(Helpers.Current.FazendaId);
                int Animais, Racoes, Pastos, Lotes;
                f.GetSumario(out Animais, out Lotes, out Racoes, out Pastos);
                ViewBag.Animais = Animais;
                ViewBag.Racoes = Racoes;
                ViewBag.Pastos = Pastos;
                ViewBag.Lotes = Lotes;
                ViewBag.Capacidades = Capacidades.ListByCriador(Helpers.Current.CriadorId);
            }                
            return View();
        }

        public ActionResult ListAnimais() 
        {
            return View();
        }

        public ActionResult ListLotes()
        {
            return View();
        }

        public ActionResult ListRacoes()
        {
            return View();
        }

        public ActionResult ListPastos() 
        {
            return View();
        }
    }
}

Interfaces/SysPec.App/Controllers/LoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SysPec.Data.Models;

namespace SysPec.App.Controllers
{
    [Authorize]
    public class LoteController : Controller
    {
        public const int _QtdMaxAnimais = 100;

        [HttpGet]
        public ActionResult Index(int? LoteId, LoteMessageId? message)
        {
            ViewBag.StatusMessage =
                message == LoteMessageId.AddSuccess ? "Lote adicionado com sucesso."
                : message == LoteMessageId.SaveSucess ? "Lote atualizado com sucesso."
                : message == LoteMessageId.Error ? "Ocorreu um erro durante a operação. Tente novamente mais tarde."
                : message == LoteMessageId.AddAnimaisSucess ? "Animais adicionados com sucesso."
                : "";

            ViewBag.LoteExiste = LoteId.HasValue && LoteId > 0;
            if (ViewBag.LoteExiste) 
                return View(new LoteModelBag { Lote = Lote.Get(LoteId.Value) });
            return View();
        }

        [HttpPost]
        public ActionResult Index(LoteModelBag model)
        {
            LoteMessageId message = LoteMessageId.Error;
            int id = 0;
            try
            {
                if (model != null)
                {
                    if (model.Lote.Id > 0)
                    {
                        model.Lote.Save();
                        id = model.Lote.Id;
                        message = LoteMessageId.SaveSucess;
                    }
                    else
                    {

                        model.Lote.Fazenda = SysPec.App.Helpers.Current.FazendaId;
                        model.Lote.Add();
                        id = model.Lote.Id;
                        addAnimaisToLote(model.Lote, model.Animal, model.QtdDeAnimais);
                        message = LoteMessageId.AddSuccess;
                    }
                }
            }
            catch (Exception)
            {
                return RedirectToAction("Index", new { message = LoteMessageId.Error });
            }
            return RedirectToAction("Index", new { LoteId = id, message = message });
        }

        [HttpGet]
        public PartialViewResult AddAnimaisToLote(int? LoteId)
        {
            ViewBag.LoteExiste = LoteId.HasValue && LoteId > 0;
            if (ViewBag.LoteExiste)
            {
                ViewBag.QtdAnimais = Lote.GetQtnAnimais(LoteId.Value);
                ViewBag.QtdAnimaisPermitida = _QtdMaxAnimais - ViewBag.QtdAnimais;
            }
            else 
            {
                ViewBag.QtdAnimais = 0;
                ViewBag.QtdAnimaisPermitida = _QtdMaxAnimais;
            }

            return PartialView();
        }

        [HttpPost]
        public ActionResult AddAnimaisToLote(LoteModelBag model) 
        {
            LoteMessageId message = LoteMessageId.Error;
            int id = 0;
            try
            {
                addAnimaisToLote(model.Lote, model.Animal, model.QtdDeAnimais);
                message = LoteMessageId.AddAnimaisSucess;
            }
            catch (Exception)
            {
                return RedirectToAction("Index", new { message = LoteMessageId.Error });
            }
            return RedirectToAction("Index", new { LoteId = id, message = message });
        }

        [HttpGet]
        public PartialViewResult Listar(int? FazendaId)
        {
            if (FazendaId.HasValue && FazendaId > 0)
                ViewBag.Lotes = Lotes.List(FazendaId.Value);
            else
                ViewBag.Lotes = Lotes.List(SysPec.App.Helpers.Current.FazendaId);

            return PartialView();
        }

        [HttpGet]
        public ActionResult ListarAnimaisDoLote(int LoteId)
        {
            ViewBag.LoteId = LoteId;
            return View();
        }

        private void addAnimaisToLote(Lote lote, Animal modelo, int Quantidade)
        {
            Animais animais = new Animais();
            for (int i = 1; i <= Quantidade; i++)
                animais.Add(new Animal
                {
                    NascidoEm = modelo.NascidoEm,
                    Peso = modelo.Peso,
                    Raca = modelo.Raca,
                    Sexo = modelo.Sexo
                });

            animais.AddAnimais(SysPec.App.Helpers.Current.FazendaId, lote.Id);   
        }
    }

    public enum LoteMessageId
    {
        AddSuccess,
        SaveSucess,
        AddAnimaisSucess,
        Error
    }
}

Interfaces/SysPec.App/Views/Aplicacao/ApresentaMensagem.cshtml
@{
    ViewBag.Title = "Mensagem";
    Layout = "~/Views/Shared/_Master.cshtml";
}
<div class="row">
    <div class="col-lg-12">
        @switch ((SysPec.App.Controllers.MessageType)ViewBag.MessageType)
        {
            case SysPec.App.Controllers.MessageType.Error:
                <div class="alert alert-danger" role="alert">
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    <span class="sr-only">Atenção:</span>
                    @ViewBag.menssagem
                </div>
                break;
            case SysPec.App.Controllers.MessageType.Sucess:
                <div class="alert alert-success" role="alert">
                    <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                    @ViewBag.menssagem
                </div>
                break;
            case SysPec.App.Controllers.MessageType.Warning:
                <div class="alert alert-warning" role="alert">
                    <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>
                    <span class="sr-only">Atenção:</span>
                    @ViewBag.menssagem
                </div>
                break;
        }
    </div>
</div>
<div class="row">
    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">@Html.ActionLink("Vacinar Lote", "PorLote", null, new { @class = "btn btn-lg btn-primary btn-block" })</div>
    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">@Html.ActionLink("Vacinar Animal", "PorAnimal", null, new { @class = "btn btn-lg btn-primary btn-block" })</div>
    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12"></div>
    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">@Html.ActionLink("Pagina Inicial", "Index", "Dashboard", null,new { @class = "btn btn-lg btn-danger btn-block" })</div>
</div>

Interfaces/SysPec.App/Views/Aplicacao/Listar.cshtml
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                @ViewBag.Titulo
            </div>
            <div class="panel-body">
                @if (ViewBag.Aplicacoes != null && ViewBag.Aplicacoes.Count > 0)
                {
                    <div class="table-responsive dataTable_wrapper">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-aplicacoes">
                            <thead>
                                <tr>
                                    @if (ViewBag.ApresentaDadoAnimais)
                                    {
                                        <th>Animal</th>
                                    }
                                    <th>Vacina</th>
                                    <th>Data de Vacinação</th>
                                    <th>Validade</th>
                                    <th>Dosagem (ml/mg)</th>
                                    <th>Método</th>
                                    @if (ViewBag.ApresentaDadoAnimais)
                                    {
                                        <th>Lote</th>
                                    }
                                    <th>Anotações</th>
                                </tr>
                            </thead>
                            <tbody>
                                @for (int i = 0; i < ViewBag.Aplicacoes.Count; i++)
                                {

                                    <tr class="@(i % 2 == 0 ? "odd" : "even") gradeA">
                                        @if (ViewBag.ApresentaDadoAnimais)
                                        {
                                            <td>
                                                <a href="@Url.Action("Index", "Animal", new { AnimalId = ViewBag.Aplicacoes[i].Animal })">
                                                    @ViewBag.Aplicacoes[i].CodigoAnimal
                                                </a>
                                            </td>
                                        }
                                        <td>@SysPec.App.Helpers.Current.Vacinas.GetNomeVacina(ViewBag.Aplicacoes[i].Vacina)</td>
                                        <td>@ViewBag.Aplicacoes[i].CriadoEm.ToString("dd/MM/yyyy")</td>
                                        <td>@(ViewBag.Aplicacoes[i].Validade != null ? ViewBag.Aplicacoes[i].Validade.ToString("dd/MM/yyyy") : "--")</td>
                                        <td>@(ViewBag.Aplicacoes[i].Dosagem.Equals(0) ? "" : ViewBag.Aplicacoes[i].Dosagem.ToString("0.00"))</td>
                                        <td>@SysPec.Data.Models.Metodos.GetNomeMetodo(ViewBag.Aplicacoes[i].Metodo)</td>
                                        @if (ViewBag.ApresentaDadoAnimais)
                                        {
                                            <td>
                                                <a href="@Url.Action("Index", "Lote", new { LoteId = ViewBag.Aplicacoes[i].Lote })">
                                                    @ViewBag.Aplicacoes[i].LoteNome
                                                </a>
                                            </td>
                                        }
                                        <td>@SysPec.App.Helpers.Helper.GetSubString(ViewBag.Aplicacoes[i].Anotacoes, 40)</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <script>
                        jQuery(function () {
                            $('#dataTables-aplicacoes').DataTable();
                        });
                    </script>
                }
                else
                {
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="alert alert-warning" role="alert">
                                <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>
                                <span class="sr-only">Atenção:</span>
                                Sem registro de vacinações
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Interfaces/SysPec.App/Views/Aplicacao/PorAnimal.cshtml
@model SysPec.Data.Models.Aplicacao
@{
    ViewBag.Title = "Vacinação por animal";
    Layout = "~/Views/Shared/_Master.cshtml";
}
@using (Html.BeginForm("Registrar", "Aplicacao", FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    if (ViewBag.AnimalExiste)
    {
        <input type="hidden" name="Animal" value="@ViewBag.Animal.Id" />
        <div class="form-group">
            <label>Animal</label>
            <input type="text" value="@ViewBag.Animal.Codigo" class="form-control" disabled />
        </div>
    }
    else
    {
        <div class="form-group">
            <label for="Animal">Animal</label>
            @Html.DropDownList("Animal", new SelectList(ViewBag.Animais, "Id", "Codigo"), "Selecione...", new { @class = "form-control"})
            @Html.ValidationMessageFor(m => m.Animal,"", new { @class = "text-danger" })
        </div>
        <script>
            $(document).ready(function () {
                $("#Animal").select2({});
            });
        </script>
    }
    @Html.Action("Editar")
    <div class="row">
        <div class="col-sm-3">
        </div>
        <div class="col-sm-6">
        </div>
        <div class="col-sm-3">
            <input type="submit" value="Registrar" class="btn btn-lg btn-success btn-block" />
        </div>
    </div>
}

Interfaces/SysPec.App/Views/Aplicacao/PorLote.cshtml
@model SysPec.Data.Models.Aplicacao
@{
    ViewBag.Title = "Vacinação por lote";
    Layout = "~/Views/Shared/_Master.cshtml";
}
@using (Html.BeginForm("Registrar", "Aplicacao", FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })    
    if (ViewBag.LoteExiste)
    {                
        <input type="hidden" name="Lote" value="@ViewBag.Lote.Id" />
        <div class="form-group">
            <label>Lote</label>
            <input type="text" value="@ViewBag.Lote.Nome" class="form-control" disabled />
        </div>
    }
    else
    {
        <div class="form-group">
            <label for="Lote">Lote</label>
            @Html.DropDownList("Lote", new SelectList(ViewBag.Lotes, "Id", "Nome"),"Selecione...", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Lote,"", new { @class = "text-danger" })
        </div>
    }
    @Html.Action("Editar")
    <div class="row">
        <div class="col-sm-3">               
        </div>
        <div class="col-sm-6">
        </div>
        <div class="col-sm-3">
            <input type="submit" value="Registrar" class="btn btn-lg btn-success btn-block" />
        </div>
    </div>
}

Interfaces/SysPec.App/Views/Aplicacao/Vacinacao.cshtml
@{
    ViewBag.Title = "Vacinacao";
    Layout = "~/Views/Shared/_Master.cshtml";    
}
@*@Html.Action("VacinacaoFormulario")*@
@if (ViewBag.Vacinas != null && ViewBag.Vacinas.Count > 0)
{
    using (Html.BeginForm("Vacinacao", "Aplicacao", FormMethod.Post, new { role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-sm-11">
                <div class="form-group">
                    @Html.DropDownList("VacinaId", new SelectList(ViewBag.Vacinas, "Id", "Nome"), "Selecione...", new { @class = "form-control", data_val = "true", data_val_number = "The field Vacina must be a number.", data_val_required = "O campo Vacina é obrigatório." })
                    <span class="field-validation-valid text-danger" data-valmsg-for="VacinaId" data-valmsg-replace="true"></span>
                </div>
            </div>
            <div class="col-sm-1">
                <button type="submit" class="btn btn-default">Executar</button>
            </div>
        </div>
    }
}
else
{
    <div class="row">
        <div class="col-lg-12">
            <div class="alert alert-warning" role="alert">
                <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>
                <span class="sr-only">Atenção:</span>
                Não existe vacinas cadastradas. Clique @Html.ActionLink("aqui", "Index", "Vacina", null, new { @class = "alert-link" }) para registrar uma nova vacina.
            </div>
        </div>
    </div>
}
@if (ViewBag.ApresantaResuldado)
{
    if (ViewBag.Aplicacoes != null && ViewBag.Aplicacoes.Count > 0)
    {
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Relatorio de Vacinação
                    </div>
                    <div class="panel-body">
                        <canvas id="VacinacaoChart"></canvas>
                        <br />
                        <br />
                        @Html.Partial("Listar")
                        <script>
    jQuery(function () {
        var ctx = $("#VacinacaoChart");

        var data = {
            labels: [
                "Animais Vacinados",
                "Animais Não Vacinados"
            ],
            datasets: [
                {
                    data: [@ViewBag.Aplicacoes.Count, @(ViewBag.QuantidadeFazendaAnimais - @ViewBag.Aplicacoes.Count)],
                    backgroundColor: [
                        "#36A2EB",
                        "#FFCE56"
                    ],
                    hoverBackgroundColor: [
                        "#36A2EB",
                        "#FFCE56"
                    ]
                }]
        };

        var animation = {
            animateScale: true
        };

        var myPieChart = new Chart(ctx, {
            type: 'doughnut',
            animation: animation,
            data: data
        });
    });
                        </script>
                        <script src="~/Scripts/Chart.min.js"></script>
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-lg-12">
                <div class="alert alert-warning" role="alert">
                    <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>
                    <span class="sr-only">Atenção:</span>
                    0 registros encontrados.
                </div>
            </div>
        </div>
    }
}

Interfaces/SysPec.App/Views/Aplicacao/VacinacaoFormulario.cshtml
@if (ViewBag.Vacinas != null && ViewBag.Vacinas.Count > 0)
{
    using (Html.BeginForm("Vacinacao", "Aplicacao", FormMethod.Post, new { role = "form" , @class = "form-inline"}))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label for="VacinaId">Vacina</label>
            @Html.DropDownList("VacinaId", new SelectList(ViewBag.Vacinas, "Id", "Nome"), "Selecione...", new { @class = "form-control"  , data_val="true" , data_val_number="The field Vacina must be a number." , data_val_required="O campo Vacina é obrigatório."})
            <span class="field-validation-valid text-danger" data-valmsg-for="VacinaId" data-valmsg-replace="true"></span>
        </div>
        <button type="submit" class="btn btn-default">Executar</button>
    }
}
else
{
    <div class="row">
        <div class="col-lg-12">
            <div class="alert alert-warning" role="alert">
                <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>
                <span class="sr-only">Atenção:</span>
                Não existe vacinas cadastradas. Clique @Html.ActionLink("aqui", "Index", "Vacina", null, new { @class = "alert-link" }) para registrar uma nova vacina.
            </div>
        </div>
    </div>
}