Interfaces/SysPec.App/Controllers/AnimalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SysPec.Data.Models;

namespace SysPec.App.Controllers
{
    [Authorize]
    public class AnimalController : Controller
    {
        [HttpGet]
        public ActionResult Index(int? AnimalId, AnimalMessageId? message, bool? ApresentaBusca)
        {
            ViewBag.StatusMessage =
                    message == AnimalMessageId.AddSuccess ? "Animal adicionado com sucesso."
                    : message == AnimalMessageId.DisableSucess ? "Animal desabilitado com sucesso."
                    : message == AnimalMessageId.Error ? "Ocorreu um erro durante a operação. Tente novamente mais tarde."
                    : "";

            if (ApresentaBusca.HasValue && ApresentaBusca.Value)
            {
                ViewBag.ApresentaBusca = true;
            }
            else
            {
                ViewBag.ApresentaBusca = false;
                ViewBag.AnimalExiste = AnimalId.HasValue && AnimalId.Value > 0;
                if (ViewBag.AnimalExiste)
                {
                    return View(Animal.Get(AnimalId.Value));
                }
                else
                {
                    Lotes lotes = Lotes.List(Helpers.Current.FazendaId);
                    Lotes lotesDisponiveis = new Lotes();
                    foreach (Lote l in lotes)
                    {
                        if (LoteController._QtdMaxAnimais > Lote.GetQtnAnimais(l.Id))
                        {
                            lotesDisponiveis.Add(l);
                        }
                    }
                    ViewBag.LotesDisponiveis = lotesDisponiveis;
                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult Index(Animal model)
        {
            AnimalMessageId message = AnimalMessageId.Error;
            int id = 0;
            try
            {
                if (model != null)
                {
                    model.Add();
                    message = AnimalMessageId.AddSuccess;
                    id = model.Id;
                }
            }
            catch (Exception)
            {
                return RedirectToAction("Index", new { message = AnimalMessageId.Error });
            }
            return RedirectToAction("Index", new { AnimalId = id, message = message });
        }

        [HttpGet]
        public ActionResult Buscar()
        {
            return RedirectToAction("Index", new { ApresentaBusca = true });
        }

        [HttpGet]
        public PartialViewResult BuscaFormulario()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult Buscar(int TipoBusca, string ValorBusca)
        {
            Animais animais = new Animais();
            switch (TipoBusca)
            {
                case 1:
                    animais = Animais.ListAnimaisByCodigo(ValorBusca, Helpers.Current.FazendaId);
                    break;
                case 2:
                    animais = Animais.ListByLoteName(ValorBusca, Helpers.Current.FazendaId);
                    break;
            }
            TempData["animais"] = animais;
            TempData["ValorBusca"] = ValorBusca;
            return View();
        }

        [HttpPost]
        public ActionResult Desabilitar(int Id)
        {
            try
            {
                if (Id > 0)
                {
                    Animal.Disable(Id);
                    return RedirectToAction("Index", new { message = AnimalMessageId.DisableSucess });
                }
                else
                    return RedirectToAction("Index", new { message = AnimalMessageId.Error });
            }
            catch (Exception)
            {
                return RedirectToAction("Index", new { message = AnimalMessageId.Error });
            }
        }

        [HttpGet]
        public PartialViewResult ListByLote(int LoteId)
        {
            ViewBag.Titulo = "Animais do Lote";
            ViewBag.Animais = Animais.ListByLote(LoteId);
            return PartialView("Listar");
        }

        [HttpGet]
        public PartialViewResult ListByFazenda(int FazendaId)
        {
            ViewBag.Titulo = "Animais da Fazenda";
            ViewBag.Animais = Animais.ListByFazenda(FazendaId);
            return PartialView("Listar");
        }

        [HttpGet]
        public PartialViewResult Listar()
        {
            return PartialView();
        }

        public enum AnimalMessageId
        {
            AddSuccess,
            DisableSucess,
            Error
        }
    }
}

Interfaces/SysPec.App/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SysPec.Data.Models;
using SysPec.Data.Estatisticas;

namespace SysPec.App.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index(int? FazendaId)
        {
            if (FazendaId.HasValue && FazendaId.Value > 0) 
                Helpers.Current.FazendaId = FazendaId.Value;

            if (Helpers.Current.FazendaId > 0)
            {
                Fazenda f = Fazenda.Get(Helpers.Current.FazendaId);
                int Animais, Racoes, Pastos, Lotes;
                f.GetSumario(out Animais, out Lotes, out Racoes, out Pastos);
                ViewBag.Animais = Animais;
                ViewBag.Racoes = Racoes;
                ViewBag.Pastos = Pastos;
                ViewBag.Lotes = Lotes;
                ViewBag.Capacidades = Capacidades.ListByCriador(Helpers.Current.CriadorId);
            }                
            return View();
        }

        public ActionResult ListAnimais() 
        {
            return View();
        }

        public ActionResult ListLotes()
        {
            return View();
        }

        public ActionResult ListRacoes()
        {
            return View();
        }

        public ActionResult ListPastos() 
        {
            return View();
        }
    }
}

Interfaces/SysPec.App/Controllers/LoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SysPec.Data.Models;

namespace SysPec.App.Controllers
{
    [Authorize]
    public class LoteController : Controller
    {
        public const int _QtdMaxAnimais = 100;

        [HttpGet]
        public ActionResult Index(int? LoteId, LoteMessageId? message)
        {
            ViewBag.StatusMessage =
                message == LoteMessageId.AddSuccess ? "Lote adicionado com sucesso."
                : message == LoteMessageId.SaveSucess ? "Lote atualizado com sucesso."
                : message == LoteMessageId.Error ? "Ocorreu um erro durante a operação. Tente novamente mais tarde."
                : message == LoteMessageId.AddAnimaisSucess ? "Animais adicionados com sucesso."
                : "";

            ViewBag.LoteExiste = LoteId.HasValue && LoteId > 0;
            if (ViewBag.LoteExiste) 
                return View(new LoteModelBag { Lote = Lote.Get(LoteId.Value) });
            return View();
        }

        [HttpPost]
        public ActionResult Index(LoteModelBag model)
        {
            LoteMessageId message = LoteMessageId.Error;
            int id = 0;
            try
            {
                if (model != null)
                {
                    if (model.Lote.Id > 0)
                    {
                        model.Lote.Save();
                        id = model.Lote.Id;
                        message = LoteMessageId.SaveSucess;
                    }
                    else
                    {

                        model.Lote.Fazenda = SysPec.App.Helpers.Current.FazendaId;
                        model.Lote.Add();
                        id = model.Lote.Id;
                        addAnimaisToLote(model.Lote, model.Animal, model.QtdDeAnimais);
                        message = LoteMessageId.AddSuccess;
                    }
                }
            }
            catch (Exception)
            {
                return RedirectToAction("Index", new { message = LoteMessageId.Error });
            }
            return RedirectToAction("Index", new { LoteId = id, message = message });
        }

        [HttpGet]
        public PartialViewResult AddAnimaisToLote(int? LoteId)
        {
            ViewBag.LoteExiste = LoteId.HasValue && LoteId > 0;
            if (ViewBag.LoteExiste)
            {
                ViewBag.QtdAnimais = Lote.GetQtnAnimais(LoteId.Value);
                ViewBag.QtdAnimaisPermitida = _QtdMaxAnimais - ViewBag.QtdAnimais;
            }
            else 
            {
                ViewBag.QtdAnimais = 0;
                ViewBag.QtdAnimaisPermitida = _QtdMaxAnimais;
            }

            return PartialView();
        }

        [HttpPost]
        public ActionResult AddAnimaisToLote(LoteModelBag model) 
        {
            LoteMessageId message = LoteMessageId.Error;
            int id = 0;
            try
            {
                addAnimaisToLote(model.Lote, model.Animal, model.QtdDeAnimais);
                message = LoteMessageId.AddAnimaisSucess;
            }
            catch (Exception)
            {
                return RedirectToAction("Index", new { message = LoteMessageId.Error });
            }
            return RedirectToAction("Index", new { LoteId = id, message = message });
        }

        [HttpGet]
        public PartialViewResult Listar(int? FazendaId)
        {
            if (FazendaId.HasValue && FazendaId > 0)
                ViewBag.Lotes = Lotes.List(FazendaId.Value);
            else
                ViewBag.Lotes = Lotes.List(SysPec.App.Helpers.Current.FazendaId);

            return PartialView();
        }

        [HttpGet]
        public ActionResult ListarAnimaisDoLote(int LoteId)
        {
            ViewBag.LoteId = LoteId;
            return View();
        }

        private void addAnimaisToLote(Lote lote, Animal modelo, int Quantidade)
        {
            Animais animais = new Animais();
            for (int i = 1; i <= Quantidade; i++)
                animais.Add(new Animal
                {
                    NascidoEm = modelo.NascidoEm,
                    Peso = modelo.Peso,
                    Raca = modelo.Raca,
                    Sexo = modelo.Sexo
                });

            animais.AddAnimais(SysPec.App.Helpers.Current.FazendaId, lote.Id);   
        }
    }

    public enum LoteMessageId
    {
        AddSuccess,
        SaveSucess,
        AddAnimaisSucess,
        Error
    }
}

Interfaces/SysPec.App/Controllers/PastoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SysPec.Data.Models;

namespace SysPec.App.Controllers
{
    [Authorize]
    public class PastoController : Controller
    {
        [HttpGet]
        public ActionResult Index(int? PastoId, PastoMessageId? message)
        {
            ViewBag.StatusMessage =
                    message == PastoMessageId.AddSuccess ? "Pasto adicionado com sucesso."
                    : message == PastoMessageId.SaveSucess ? "Pasto atualizado com sucesso."
                    : message == PastoMessageId.Error ? "Ocorreu um erro durante a operação. Tente novamente mais tarde."
                    : "";

            ViewBag.PastoExiste = PastoId.HasValue && PastoId > 0;
            if (ViewBag.PastoExiste)
                return View(Pasto.Get(PastoId.Value));

            return View();
        }

        [HttpPost]
        public ActionResult Index(Pasto pasto)
        {
            PastoMessageId message = PastoMessageId.Error;
            int id = 0;
            try
            {
                if (pasto != null)
                {
                    if (pasto.Id > 0)
                    {
                        pasto.Save();
                        id = pasto.Id;
                        message = PastoMessageId.SaveSucess;
                    }
                    else
                    {
                        pasto.Fazenda = SysPec.App.Helpers.Current.FazendaId;
                        pasto.Add();
                        id = pasto.Id;
                        message = PastoMessageId.AddSuccess;
                    }
                }
            }
            catch (Exception)
            {
                return RedirectToAction("Index", new { message = PastoMessageId.Error });
            }
            return RedirectToAction("Index", new { PastoId = id, message = message });
        }

        [HttpGet]
        public PartialViewResult Listar(int? FazendaId)
        {
            if (FazendaId.HasValue && FazendaId > 0)
                ViewBag.Pastos = Pastos.List(FazendaId.Value);
            else 
                ViewBag.Pastos = Pastos.List(SysPec.App.Helpers.Current.FazendaId);

            return PartialView();
        }

        [HttpGet]
        public PartialViewResult Capacidade()
        {
            ViewBag.Pastos = Pastos.List(SysPec.App.Helpers.Current.FazendaId);              
            return PartialView();
        }

        public enum PastoMessageId
        {
            AddSuccess,
            SaveSucess,
            Error
        }
    }
}

Interfaces/SysPec.App/Controllers/RacoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SysPec.Data.Models;

namespace SysPec.App.Controllers
{
    [Authorize]
    public class RacaoController : Controller
    {
        // GET: Racoes
        [HttpGet]
        public ActionResult Index(int? RacaoId, RacoesMessageId? message)
        {
            ViewBag.StatusMessage =
            message == RacoesMessageId.AddSuccess ? "Ração adicionada com sucesso."
            : message == RacoesMessageId.SaveSucess ? "Ração atualizada com sucesso."
            : message == RacoesMessageId.Error ? "Ocorreu um erro durante a operação. Tente novamente mais tarde."
            : "";

            ViewBag.RacaoExiste = RacaoId.HasValue && RacaoId > 0;
            if (ViewBag.RacaoExiste)
                return View(Racao.Get(RacaoId.Value));
            return View();
        }

        [HttpPost]
        public ActionResult Index(Racao racao)
        {
            RacoesMessageId message = RacoesMessageId.Error;
            int id = 0;
            try
            {
                if (racao != null)
                {
                    if (racao.Id > 0)
                    {
                        racao.Save();
                        id = racao.Id;
                        message = RacoesMessageId.SaveSucess;
                    }
                    else
                    {
                        racao.Criador = Helpers.Current.CriadorId;
                        racao.Add();
                        id = racao.Id;
                        Helpers.Current.Racoes = Racoes.ListByCriador(Helpers.Current.CriadorId);
                        message = RacoesMessageId.AddSuccess;
                    }
                }
            }
            catch (Exception)
            {
                return RedirectToAction("Index", new { message = VacinaMessageId.Error });
            }
            return RedirectToAction("Index", new { RacaoId = id, message = message });
        }

        [HttpGet]
        public PartialViewResult Listar()
        {
            ViewBag.Racoes = Racoes.ListByCriador(Helpers.Current.CriadorId);
            return PartialView();
        }
    }

    public enum RacoesMessageId
    {
        AddSuccess,
        SaveSucess,
        Error
    }
}

Interfaces/SysPec.App/Views/Dashboard/Index.cshtml
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_Master.cshtml";
}

@if (SysPec.App.Helpers.Current.FazendaId > 0)
{
    <div class="row">
        <div class="col-lg-4 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-ra fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">@ViewBag.Animais</div>
                            <div>Animais</div>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("ListAnimais")">
                    <div class="panel-footer">
                        <span class="pull-left">Visualizar detalhes</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-4 col-md-6">
            <div class="panel panel-yellow">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-cubes fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">@ViewBag.Lotes</div>
                            <div>Lotes</div>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("ListLotes")">
                    <div class="panel-footer">
                        <span class="pull-left">Visualizar detalhes</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-4 col-md-6">
            <div class="panel panel-green">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-tree fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">@ViewBag.Pastos</div>
                            <div>Pastos</div>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("ListPastos")">
                    <div class="panel-footer">
                        <span class="pull-left">Visualizar detalhes</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-external-link-square fa-fw"></i> Links Úteis
                </div>
                <div class="panel-body">
                    <div class="list-group">
                        <a href="https://www.scotconsultoria.com.br/cotacoes/boi-gordo/" target="_blank" class="list-group-item">
                            <i class="fa fa-bar-chart-o fa-fw"></i> Cotação da arroba do boi gordo
                        </a>
                        <a href="http://revistagloborural.globo.com/" target="_blank" class="list-group-item">
                            <i class="fa fa-comments-o fa-fw"></i> Notícias do Campo
                        </a>
                        <a href="https://www.embrapa.br/" target="_blank" class="list-group-item">
                            <i class="fa fa-trophy fa-fw"></i> Embrapa
                        </a>
                        <a href="http://www.agricultura.gov.br/animal/especies/bovinos-e-bubalinos" target="_blank" class="list-group-item">
                            <i class="fa fa-home fa-fw"></i> Ministério da Agricultura
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="panel panel-red">
                <div class="panel-heading">
                    <i class="fa fa-bar-chart-o fa-fw"></i> Nível de Utilização
                </div>
                <div class="panel-body">
                    @foreach (SysPec.Data.Estatisticas.CapacidadeUtilizada C in ViewBag.Capacidades)
                    {
                        <div>
                            <div>
                                <p>
                                    <strong>@C.FazendaNome</strong>
                                    <span class="pull-right text-muted">@C.PorcentagemFormatada da capacidade</span>
                                </p>
                                <div class="progress progress-striped active">
                                    <div class="progress-bar @(C.Porcentagem <= 49 ? "progress-bar-success" : C.Porcentagem <= 79 ? "progress-bar-warning" : "progress-bar-danger")" role="progressbar" aria-valuenow="@C.Porcentagem" aria-valuemin="0" aria-valuemax="100" style="width: @C.Porcentagem%">
                                        <span class="sr-only">@C.PorcentagemFormatada Utilizada</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
}
else
{
    <div class="row">
        <div class="col-lg-12">
            <div class="alert alert-warning" role="alert">
                <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>
                <span class="sr-only">Atenção:</span>
                Não existe fazendas cadastradas. Clique @Html.ActionLink("aqui", "Index", "Fazenda", null, new { @class = "alert-link" }) para registrar uma nova fazenda.
            </div>
        </div>
    </div>
}

Interfaces/SysPec.App/Views/Dashboard/ListAnimais.cshtml
@{
    ViewBag.Title = "Animais da Fazenda";
    Layout = "~/Views/Shared/_Master.cshtml";
}
@Html.Action("ListByFazenda", "Animal", new { FazendaId = SysPec.App.Helpers.Current.FazendaId });
<br />
<div class="row">
    <div class="col-lg-3">
        @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-lg btn-danger btn-block" })
    </div>
</div>

Interfaces/SysPec.App/Views/Dashboard/ListLotes.cshtml
@{
    ViewBag.Title = "Lotes da Fazenda";
    Layout = "~/Views/Shared/_Master.cshtml";
}
@{
    ViewBag.Title = "Animais da Fazenda";
    Layout = "~/Views/Shared/_Master.cshtml";
}
@Html.Action("Listar", "Lote");
<br />
<div class="row">
    <div class="col-lg-3">
        @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-lg btn-danger btn-block" })
    </div>
</div>

Interfaces/SysPec.App/Views/Dashboard/ListPastos.cshtml
@{
    ViewBag.Title = "Pastos da Fazenda";
    Layout = "~/Views/Shared/_Master.cshtml";
}
@Html.Action("Listar", "Pasto");
<br />
<div class="row">
    <div class="col-lg-3">
        @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-lg btn-danger btn-block" })
    </div>
</div>

Interfaces/SysPec.App/Views/Dashboard/ListRacoes.cshtml
@{
    ViewBag.Title = "Racões da Fazenda";
    Layout = "~/Views/Shared/_Master.cshtml";
}
@Html.Action("Listar", "Racao");
<br />
<div class="row">
    <div class="col-lg-3">
        @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-lg btn-danger btn-block" })
    </div>
</div>