Interfaces/SysPec.App/Controllers/AlimentacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SysPec.Data.Models;
using SysPec.App.Helpers;

namespace SysPec.App.Controllers
{
    [Authorize]
    public class AlimentacaoController : Controller
    {
        // GET: Alimentacao
        public ActionResult Index()
        {
            Lotes lotes = Lotes.List(Current.FazendaId);
            ViewBag.Lotes = new Lotes();
            if (lotes != null && lotes.Count > 0)
                foreach (Lote l in lotes)
                    if (Lote.GetQtnAnimais(l.Id) > 0)
                        ViewBag.Lotes.Add(l);
            if (ViewBag.Lotes.Count <= 0)
                return RedirectToAction("ApresentaMensagem", new { menssagem = "Não existe lotes com animais disponíveis", message = MessageType.Warning });
            return View();
        }

        [HttpGet]
        public ActionResult PorLote(int LoteId)
        {
            ViewBag.LoteExiste = LoteId > 0;
            if (ViewBag.LoteExiste) 
            {
                ViewBag.Lote = Lote.Get(LoteId);                
                Pastos pastos = Pastos.List(Current.FazendaId);
                int QuantidadeAtualLote = Lote.GetQtnAnimais(ViewBag.Lote.Id);
                ViewBag.Pastos = new Pastos();
                if (pastos != null && pastos.Count > 0)
                    foreach (Pasto p in pastos)
                        if ((p.GetQtnAnimais() + QuantidadeAtualLote) < p.QtdAnimaisSuporte)
                            ViewBag.Pastos.Add(p);

                if (ViewBag.Pastos.Count <= 0)
                    return RedirectToAction("ApresentaMensagem", new { menssagem = "Não existe pastos disponíveis", message = MessageType.Warning });
            }
            return View();
        }

        [HttpPost]
        public ActionResult Registrar(Alimentacao model)
        {
            try
            {
                if (model != null)
                {
                    if (model.Animal > 0)
                        model.Add();
                    else
                        model.AddReplicandoParaLote();
                    return RedirectToAction("ApresentaMensagem", new { menssagem = "Alimentação registrada com sucesso!", message = MessageType.Sucess });
                }
                else
                {
                    return RedirectToAction("ApresentaMensagem", new { menssagem = "Não foi possível registrar a alimentação. Dados invalídos!", message = MessageType.Warning });
                }
            }
            catch (Exception)
            {
                return RedirectToAction("ApresentaMensagem", new { menssagem = "Desulpe! Não foi possível registrar a alimentação. Erro desconhecido!", message = MessageType.Error });
            }
        }

        [HttpGet]
        public ActionResult Editar()
        {
            Pastos pastos = Pastos.List(Current.FazendaId);
            if (pastos.Count <= 0)
                return RedirectToAction("ApresentaMensagem", new { menssagem = "Não existe pastos cadastradas", message = MessageType.Warning });
            ViewBag.Pastos = pastos;
            return PartialView();
        }

        [HttpGet]
        public ActionResult ApresentaMensagem(string menssagem, MessageType message)
        {
            ViewBag.Menssagem = menssagem;
            ViewBag.MessageType = message;
            return View();
        }

        [HttpGet]
        public PartialViewResult ListByAnimal(int AnimalId)
        {
            ViewBag.Titulo = "Historico Alimentar";
            Alimentacoes A = Alimentacoes.ListByAnimal(AnimalId);
            ViewBag.Alimentacoes = A;
            ViewBag.ApresentaDadoAnimais = false;

            if (A != null && A.Count > 0) 
            {
                ViewBag.ApresentaGrafico = true;
                ViewBag.Datas = TransformaDataEmString(A);
                ViewBag.Pesos = TransformaPesoEmString(A);
            }
            return PartialView("Listar");
        }

        [HttpGet]
        public PartialViewResult Listar()
        {
            return PartialView();
        }

        private string TransformaDataEmString(Alimentacoes Al) 
        {
            string r = string.Empty;
            if (Al != null & Al.Count > 0) 
            {
                foreach (Alimentacao A in Al)
                    r += string.Format("'{0}',",A.CriadoEm.ToString("dd/MM/yyyy"));
                r = r.Substring(0,r.Length -1);
            }
            return r;
        }

        private string TransformaPesoEmString(Alimentacoes Al)
        {
            string r = string.Empty;
            if (Al != null & Al.Count > 0)
            {
                foreach (Alimentacao A in Al)
                    r += string.Format("{0},", A.Peso);
                r = r.Substring(0, r.Length - 1);
            }
            return r;
        }
    }

    public enum MessageType
    {
        Error,
        Sucess,
        Warning
    }

}

Interfaces/SysPec.App/Controllers/AnimalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SysPec.Data.Models;

namespace SysPec.App.Controllers
{
    [Authorize]
    public class AnimalController : Controller
    {
        [HttpGet]
        public ActionResult Index(int? AnimalId, AnimalMessageId? message, bool? ApresentaBusca)
        {
            ViewBag.StatusMessage =
                    message == AnimalMessageId.AddSuccess ? "Animal adicionado com sucesso."
                    : message == AnimalMessageId.DisableSucess ? "Animal desabilitado com sucesso."
                    : message == AnimalMessageId.Error ? "Ocorreu um erro durante a operação. Tente novamente mais tarde."
                    : "";

            if (ApresentaBusca.HasValue && ApresentaBusca.Value)
            {
                ViewBag.ApresentaBusca = true;
            }
            else
            {
                ViewBag.ApresentaBusca = false;
                ViewBag.AnimalExiste = AnimalId.HasValue && AnimalId.Value > 0;
                if (ViewBag.AnimalExiste)
                {
                    return View(Animal.Get(AnimalId.Value));
                }
                else
                {
                    Lotes lotes = Lotes.List(Helpers.Current.FazendaId);
                    Lotes lotesDisponiveis = new Lotes();
                    foreach (Lote l in lotes)
                    {
                        if (LoteController._QtdMaxAnimais > Lote.GetQtnAnimais(l.Id))
                        {
                            lotesDisponiveis.Add(l);
                        }
                    }
                    ViewBag.LotesDisponiveis = lotesDisponiveis;
                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult Index(Animal model)
        {
            AnimalMessageId message = AnimalMessageId.Error;
            int id = 0;
            try
            {
                if (model != null)
                {
                    model.Add();
                    message = AnimalMessageId.AddSuccess;
                    id = model.Id;
                }
            }
            catch (Exception)
            {
                return RedirectToAction("Index", new { message = AnimalMessageId.Error });
            }
            return RedirectToAction("Index", new { AnimalId = id, message = message });
        }

        [HttpGet]
        public ActionResult Buscar()
        {
            return RedirectToAction("Index", new { ApresentaBusca = true });
        }

        [HttpGet]
        public PartialViewResult BuscaFormulario()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult Buscar(int TipoBusca, string ValorBusca)
        {
            Animais animais = new Animais();
            switch (TipoBusca)
            {
                case 1:
                    animais = Animais.ListAnimaisByCodigo(ValorBusca, Helpers.Current.FazendaId);
                    break;
                case 2:
                    animais = Animais.ListByLoteName(ValorBusca, Helpers.Current.FazendaId);
                    break;
            }
            TempData["animais"] = animais;
            TempData["ValorBusca"] = ValorBusca;
            return View();
        }

        [HttpPost]
        public ActionResult Desabilitar(int Id)
        {
            try
            {
                if (Id > 0)
                {
                    Animal.Disable(Id);
                    return RedirectToAction("Index", new { message = AnimalMessageId.DisableSucess });
                }
                else
                    return RedirectToAction("Index", new { message = AnimalMessageId.Error });
            }
            catch (Exception)
            {
                return RedirectToAction("Index", new { message = AnimalMessageId.Error });
            }
        }

        [HttpGet]
        public PartialViewResult ListByLote(int LoteId)
        {
            ViewBag.Titulo = "Animais do Lote";
            ViewBag.Animais = Animais.ListByLote(LoteId);
            return PartialView("Listar");
        }

        [HttpGet]
        public PartialViewResult ListByFazenda(int FazendaId)
        {
            ViewBag.Titulo = "Animais da Fazenda";
            ViewBag.Animais = Animais.ListByFazenda(FazendaId);
            return PartialView("Listar");
        }

        [HttpGet]
        public PartialViewResult Listar()
        {
            return PartialView();
        }

        public enum AnimalMessageId
        {
            AddSuccess,
            DisableSucess,
            Error
        }
    }
}

Interfaces/SysPec.App/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SysPec.Data.Models;
using SysPec.Data.Estatisticas;

namespace SysPec.App.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index(int? FazendaId)
        {
            if (FazendaId.HasValue && FazendaId.Value > 0) 
                Helpers.Current.FazendaId = FazendaId.Value;

            if (Helpers.Current.FazendaId > 0)
            {
                Fazenda f = Fazenda.Get(Helpers.Current.FazendaId);
                int Animais, Racoes, Pastos, Lotes;
                f.GetSumario(out Animais, out Lotes, out Racoes, out Pastos);
                ViewBag.Animais = Animais;
                ViewBag.Racoes = Racoes;
                ViewBag.Pastos = Pastos;
                ViewBag.Lotes = Lotes;
                ViewBag.Capacidades = Capacidades.ListByCriador(Helpers.Current.CriadorId);
            }                
            return View();
        }

        public ActionResult ListAnimais() 
        {
            return View();
        }

        public ActionResult ListLotes()
        {
            return View();
        }

        public ActionResult ListRacoes()
        {
            return View();
        }

        public ActionResult ListPastos() 
        {
            return View();
        }
    }
}

Interfaces/SysPec.App/Controllers/LoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SysPec.Data.Models;

namespace SysPec.App.Controllers
{
    [Authorize]
    public class LoteController : Controller
    {
        public const int _QtdMaxAnimais = 100;

        [HttpGet]
        public ActionResult Index(int? LoteId, LoteMessageId? message)
        {
            ViewBag.StatusMessage =
                message == LoteMessageId.AddSuccess ? "Lote adicionado com sucesso."
                : message == LoteMessageId.SaveSucess ? "Lote atualizado com sucesso."
                : message == LoteMessageId.Error ? "Ocorreu um erro durante a operação. Tente novamente mais tarde."
                : message == LoteMessageId.AddAnimaisSucess ? "Animais adicionados com sucesso."
                : "";

            ViewBag.LoteExiste = LoteId.HasValue && LoteId > 0;
            if (ViewBag.LoteExiste) 
                return View(new LoteModelBag { Lote = Lote.Get(LoteId.Value) });
            return View();
        }

        [HttpPost]
        public ActionResult Index(LoteModelBag model)
        {
            LoteMessageId message = LoteMessageId.Error;
            int id = 0;
            try
            {
                if (model != null)
                {
                    if (model.Lote.Id > 0)
                    {
                        model.Lote.Save();
                        id = model.Lote.Id;
                        message = LoteMessageId.SaveSucess;
                    }
                    else
                    {

                        model.Lote.Fazenda = SysPec.App.Helpers.Current.FazendaId;
                        model.Lote.Add();
                        id = model.Lote.Id;
                        addAnimaisToLote(model.Lote, model.Animal, model.QtdDeAnimais);
                        message = LoteMessageId.AddSuccess;
                    }
                }
            }
            catch (Exception)
            {
                return RedirectToAction("Index", new { message = LoteMessageId.Error });
            }
            return RedirectToAction("Index", new { LoteId = id, message = message });
        }

        [HttpGet]
        public PartialViewResult AddAnimaisToLote(int? LoteId)
        {
            ViewBag.LoteExiste = LoteId.HasValue && LoteId > 0;
            if (ViewBag.LoteExiste)
            {
                ViewBag.QtdAnimais = Lote.GetQtnAnimais(LoteId.Value);
                ViewBag.QtdAnimaisPermitida = _QtdMaxAnimais - ViewBag.QtdAnimais;
            }
            else 
            {
                ViewBag.QtdAnimais = 0;
                ViewBag.QtdAnimaisPermitida = _QtdMaxAnimais;
            }

            return PartialView();
        }

        [HttpPost]
        public ActionResult AddAnimaisToLote(LoteModelBag model) 
        {
            LoteMessageId message = LoteMessageId.Error;
            int id = 0;
            try
            {
                addAnimaisToLote(model.Lote, model.Animal, model.QtdDeAnimais);
                message = LoteMessageId.AddAnimaisSucess;
            }
            catch (Exception)
            {
                return RedirectToAction("Index", new { message = LoteMessageId.Error });
            }
            return RedirectToAction("Index", new { LoteId = id, message = message });
        }

        [HttpGet]
        public PartialViewResult Listar(int? FazendaId)
        {
            if (FazendaId.HasValue && FazendaId > 0)
                ViewBag.Lotes = Lotes.List(FazendaId.Value);
            else
                ViewBag.Lotes = Lotes.List(SysPec.App.Helpers.Current.FazendaId);

            return PartialView();
        }

        [HttpGet]
        public ActionResult ListarAnimaisDoLote(int LoteId)
        {
            ViewBag.LoteId = LoteId;
            return View();
        }

        private void addAnimaisToLote(Lote lote, Animal modelo, int Quantidade)
        {
            Animais animais = new Animais();
            for (int i = 1; i <= Quantidade; i++)
                animais.Add(new Animal
                {
                    NascidoEm = modelo.NascidoEm,
                    Peso = modelo.Peso,
                    Raca = modelo.Raca,
                    Sexo = modelo.Sexo
                });

            animais.AddAnimais(SysPec.App.Helpers.Current.FazendaId, lote.Id);   
        }
    }

    public enum LoteMessageId
    {
        AddSuccess,
        SaveSucess,
        AddAnimaisSucess,
        Error
    }
}

Interfaces/SysPec.App/Views/Alimentacao/ApresentaMensagem.cshtml
@{
    ViewBag.Title = "Mensagem";
    Layout = "~/Views/Shared/_Master.cshtml";
}
<div class="row">
    <div class="col-lg-12">
        @switch ((SysPec.App.Controllers.MessageType)ViewBag.MessageType)
        {
            case SysPec.App.Controllers.MessageType.Error:
                <div class="alert alert-danger" role="alert">
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    <span class="sr-only">Atenção:</span>
                    @ViewBag.menssagem
                </div>
                break;
            case SysPec.App.Controllers.MessageType.Sucess:
            <div class="alert alert-success" role="alert">
                <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                @ViewBag.menssagem
            </div>
                break;
            case SysPec.App.Controllers.MessageType.Warning:
            <div class="alert alert-warning" role="alert">
                <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>
                <span class="sr-only">Atenção:</span>
                @ViewBag.menssagem
            </div>
                break;
        }
    </div>
</div>
<div class="row">
    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">@Html.ActionLink("Alimentar Lote", "Index", null, new { @class = "btn btn-lg btn-primary btn-block" })</div>
    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12"></div>
    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12"></div>
    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">@Html.ActionLink("Pagina Inicial", "Index", "Dashboard", null, new { @class = "btn btn-lg btn-danger btn-block" })</div>
</div>

Interfaces/SysPec.App/Views/Alimentacao/Editar.cshtml
@model SysPec.Data.Models.Alimentacao
<div class="form-group">
    @Html.LabelFor(m => m.Racao)
    @Html.DropDownList("Racao", new SelectList(SysPec.App.Helpers.Current.Racoes, "Id", "Nome"), new { @class = "form-control" })
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Pasto)
    @Html.DropDownList("Pasto", new SelectList(ViewBag.Pastos, "Id", "Nome"), "Selecione...", new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.Pasto, "", new { @class = "text-danger" })
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Peso)
    <div class="input-group">
        @Html.TextBoxFor(m => m.Peso, new { @class = "form-control", type = "number" })
        <div class="input-group-addon">(ml,mg)</div>
    </div>
    @Html.ValidationMessageFor(m => m.Peso, "", new { @class = "text-danger" })
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Anotacoes)
    @Html.TextAreaFor(m => m.Anotacoes, new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.Anotacoes, "", new { @class = "text-danger" })
</div>

Interfaces/SysPec.App/Views/Alimentacao/Index.cshtml
@{
    ViewBag.Title = "Alimentação";
    Layout = "~/Views/Shared/_Master.cshtml";
}
@using (Html.BeginForm("PorLote", "Alimentacao", FormMethod.Get, new { role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row">
        <div class="col-sm-11">
            <div class="form-group">
                @Html.DropDownList("LoteId", new SelectList(ViewBag.Lotes, "Id", "Nome"), "Selecione um lote", new { @class = "form-control", data_val = "true", data_val_number = "The field Lote must be a number.", data_val_required = "O campo Lote é obrigatório." })
                <span class="field-validation-valid text-danger" data-valmsg-for="LoteId" data-valmsg-replace="true"></span>
            </div>
        </div>
        <div class="col-sm-1">
            <button type="submit" class="btn btn-default">Selecionar</button>
        </div>
    </div>
}

Interfaces/SysPec.App/Views/Alimentacao/Listar.cshtml
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                @ViewBag.Titulo
            </div>
            <div class="panel-body">
                @if (ViewBag.Alimentacoes != null && ViewBag.Alimentacoes.Count > 0)
                {
                    <div class="table-responsive dataTable_wrapper">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-alimentacoes">
                            <thead>
                                <tr>
                                    @if (ViewBag.ApresentaDadoAnimais)
                                    {
                                        <th>Animal</th>
                                    }
                                    <th>Ração</th>
                                    <th>Data de Inclusão</th>
                                    <th>Data de Saída</th>
                                    <th>Pasto</th>
                                    @if (ViewBag.ApresentaDadoAnimais)
                                    {
                                        <th>Lote</th>
                                    }
                                    <th>Anotações</th>
                                </tr>
                            </thead>
                            <tbody>
                                @for (int i = 0; i < ViewBag.Alimentacoes.Count; i++)
                                {

                                    <tr class="@(i % 2 == 0 ? "odd" : "even") gradeA">
                                        @if (ViewBag.ApresentaDadoAnimais)
                                        {
                                            <td>
                                                <a href="@Url.Action("Index", "Animal", new { AnimalId = ViewBag.Alimentacoes[i].Animal })">
                                                    @ViewBag.Alimentacoes[i].CodigoAnimal
                                                </a>
                                            </td>
                                        }
                                        <td>@SysPec.App.Helpers.Current.Racoes.GetNomeRacao(ViewBag.Alimentacoes[i].Racao)</td>
                                        <td>@ViewBag.Alimentacoes[i].CriadoEm.ToString("dd/MM/yyyy")</td>

                                        @if (ViewBag.Alimentacoes[i].Antigo)
                                        {
                                            <td>@ViewBag.Alimentacoes[i + 1].CriadoEm.ToString("dd/MM/yyyy")</td>
                                        }
                                        else
                                        {
                                            <td>Atual</td>
                                        }

                                        <td>@ViewBag.Alimentacoes[i].PastoNome</td>
                                        @if (ViewBag.ApresentaDadoAnimais)
                                        {
                                            <td>
                                                <a href="@Url.Action("Index", "Lote", new { LoteId = ViewBag.Alimentacoes[i].Lote })">
                                                    @ViewBag.Alimentacoes[i].LoteNome
                                                </a>
                                            </td>
                                        }
                                        <td>@SysPec.App.Helpers.Helper.GetSubString(ViewBag.Alimentacoes[i].Anotacoes, 40)</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <script>
                        jQuery(function () {
                            $('#dataTables-alimentacoes').DataTable();
                        });
                    </script>

                    if (ViewBag.ApresentaGrafico)
                    {
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                Histórico De Ganho De Peso
                            </div>
                            <div class="panel-body">
                                <canvas id="AlimentacaoChart"></canvas>
                                <br />
                                <br />
                            </div>
                        </div>

                        <script>
                            jQuery(function () {

                                var ctx = $("#AlimentacaoChart");

                                var animation = {
                                    animateScale: true
                                };

                                var data = {
                                    labels: [@Html.Raw(ViewBag.Datas)],
                                    datasets: [
                                        {
                                            label: 'Peso (Kg)',
                                            fill: false,
                                            lineTension: 0.1,
                                            backgroundColor: 'rgba(75,192,192,0.4)',
                                            borderColor: 'rgba(75,192,192,1)',
                                            borderCapStyle: 'butt',
                                            borderDash: [],
                                            borderDashOffset: 0.0,
                                            borderJoinStyle: 'miter',
                                            pointBorderColor: 'rgba(75,192,192,1)',
                                            pointBackgroundColor: '#fff',
                                            pointBorderWidth: 1,
                                            pointHoverRadius: 5,
                                            pointHoverBackgroundColor: 'rgba(75,192,192,1)',
                                            pointHoverBorderColor: 'rgba(220,220,220,1)',
                                            pointHoverBorderWidth: 2,
                                            pointRadius: 1,
                                            pointHitRadius: 10,
                                            data: [@ViewBag.Pesos],
                                        }
                                    ]
                                };

                                var myLineChart = new Chart(ctx, {
                                    type: 'line',
                                    data: data
                                });

                            });
                        </script>
                        <script src="~/Scripts/Chart.min.js"></script>
                    }
                }
                else
                {
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="alert alert-warning" role="alert">
                                <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>
                                <span class="sr-only">Atenção:</span>
                                Sem registro de alimentações
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Interfaces/SysPec.App/Views/Alimentacao/PorLote.cshtml
@model SysPec.Data.Models.Alimentacao
@{
    ViewBag.Title = "Alimentação por lote";
    Layout = "~/Views/Shared/_Master.cshtml";
}
@using (Html.BeginForm("Registrar", "Alimentacao", FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    if (ViewBag.LoteExiste)
    {
        <input type="hidden" name="Lote" value="@ViewBag.Lote.Id" />
        <div class="form-group">
            <label>Lote</label>
            <input type="text" value="@ViewBag.Lote.Nome" class="form-control" disabled />
        </div>
    }
    else
    {
        <div class="form-group">
            <label for="Lote">Lote</label>
            @Html.DropDownList("Lote", new SelectList(ViewBag.Lotes, "Id", "Nome"), "Selecione...", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Lote, "", new { @class = "text-danger" })
        </div>
    }
    @Html.Action("Editar")
    <div class="row">
        <div class="col-sm-3">
        </div>
        <div class="col-sm-6">
        </div>
        <div class="col-sm-3">
            <input type="submit" value="Registrar" class="btn btn-lg btn-success btn-block" />
        </div>
    </div>
}